# Generated by Django 6.1 on 2026-08-15 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(help_text='Hex color, e.g. #4287f5', max_length=7)),
                ('weekly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. UHFCU Credit', max_length=100)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_column', models.CharField(max_length=100)),
                ('description_column', models.CharField(max_length=100)),
                ('amount_column', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_column', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_column', models.CharField(blank=True, max_length=100, null=True)),
                ('flip_sign', models.BooleanField(default=False, help_text='Flip the sign of parsed amounts (e.g. bank exports spend as positive)')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column_mapping', to='expenses.card')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_rules', to='expenses.category')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('import', 'Import'), ('voice', 'Voice')], default='import', max_length=10)),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.card')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expenses.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
