# Generated by Django 6.1 on 2026-08-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='header_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
