# Generated by Django 6.1 on 2026-08-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_columnmapping_header_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='category_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='imported_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
