# Generated by Django 6.1 on 2026-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_columnmapping_category_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnmapping',
            name='header_row',
        ),
        migrations.AddField(
            model_name='card',
            name='header_row',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
