# Generated by Django 6.1 on 2026-08-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_columnmapping_header_row_card_header_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='imported_category',
        ),
    ]
