# Generated by Django 6.1 on 2026-08-15 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='alt_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expenses.card'),
        ),
        migrations.AddField(
            model_name='columnmapping',
            name='type_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
