# Generated by Django 6.1 on 2026-08-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_columnmapping_alt_card_columnmapping_type_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. SoFi Savings, Robinhood, Student Loan', max_length=100)),
                ('category', models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('loan', 'Loan'), ('asset', 'Other asset'), ('liability', 'Other liability')], max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'category', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='YearlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_expense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetWorthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, help_text="Always positive - sign comes from the account's category", max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='expenses.networthaccount')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
