# Generated by Django 6.1 on 2026-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_networthaccount_yearlyexpense_networthentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyexpense',
            name='owner',
        ),
        migrations.AddField(
            model_name='yearlyexpense',
            name='scope',
            field=models.CharField(choices=[('household', 'Household'), ('soroush', 'Soroush'), ('shiva', 'Shiva')], default='household', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
