# Generated by Django 6.1 on 2026-08-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_tag_transaction_location_transaction_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('import', 'Import'), ('voice', 'Voice'), ('manual', 'Manual')], default='import', max_length=10),
        ),
    ]
