# Generated by Django 6.1 on 2026-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='incomes', to='expenses.tag'),
        ),
    ]
